# Taken from https://github.com/itzmeanjan/ascon/blob/644e5c0ee64da42e3c187adb84ba4c43925caf30/.github/workflows/test_ci.yml
name: Test Binary Fuse Filter over Zp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++, clang++]
      max-parallel: 4

    steps:
      - uses: actions/checkout@v4

      - name: Setup Google Test
        uses: Bacondish2023/setup-googletest@v1
        with:
          tag: v1.15.2


      - name: Build and Test (${{ matrix.os }}, ${{ matrix.compiler }})
        run: |
          CXX=${{ matrix.compiler }} make -j
