# Taken from https://github.com/itzmeanjan/ascon/blob/644e5c0ee64da42e3c187adb84ba4c43925caf30/.github/workflows/test_ci.yml
name: Test Binary Fuse Filter for Key-Value Map

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++, clang++]
        build_type: [debug, release]
        test_type: [standard, asan, ubsan]
      max-parallel: 4

    steps:
      - uses: actions/checkout@v4

      - name: Setup Google Test
        uses: Bacondish2023/setup-googletest@v1
        with:
          tag: v1.15.2


      - name: Build and Test (${{ matrix.os }}, ${{ matrix.compiler }}, ${{ matrix.build_type }}, ${{ matrix.test_type }})
        run: |
          CXX=${{ matrix.compiler }}
          if [[ ${{ matrix.test_type }} == "standard" ]]; then
            make test -j 2>&1 | tee build.log
          else
            make ${{ matrix.build_type }}_${{ matrix.test_type }}_test -j 2>&1 | tee build.log
          fi
          if [ $? -ne 0 ]; then
            echo "Build or Test Failed! See build.log for details."
            exit 1
          fi

      - name: Upload Build Log
        uses: actions/upload-artifact@v3
        with:
          name: build-log-${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.test_type }}
          path: build.log
